### ISSUE TITLE
Add bg task to periodically fetch new notifications and badge icon

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/Freetime#125]
Should be pretty simple I think.

Do we want a setting for this? I know people can enable/disable badges in Settings.app, but maybe an actual setting would be good too? Or maybe we disable it by default, put it in settings, and then when enabling is where we display the "Allow notifications" or w/e prompt (or does local badging even need that?).

**Comment by BasThomas** [comment]
Yep, [seems like it.](https://developer.apple.com/documentation/usernotifications/unusernotificationcenter) Putting it in Settings w/ the "Allow Notifications" would work best, I think.

**Comment by ArtSabintsev** [comment]
+1.

A couple years back, I did a bit of work on the Narwhal Reddit client (getnarwhal.com). This was one of the features I added, as there was no webhook or APNs server in place. If you do it right, a user will get notifications via any of the traditional notification methods (badge, sound, banner), but they'll be on a delay of 10-30 minutes, since this is achieved using `Background Fetch` that pushes a `Local Notification`. 

The background fetch is executed 2-3 times per hour (if you're lucky), but once it executes, you can push a notification. For this to work, the user must keep the app backgrounded (not forced-closed).

So, get this feature 100% right, without webhooks and an APNs server, you need to do a few things:

- Enable Background Fetch
- Opt-in to Local Notifications (with option to toggle this in Settings)
- Handle notification when app is background
- Handle notification when app is already in foreground with some type of toast/UI-notification.

Just my 2 cents. I'm happy to contribute to this feature (as early as September 2017), if you're still interested in implementing something like this in Freetime.

**Comment by rnystrom** [comment]
Done!

**Comment by ArtSabintsev** [comment]
Awesome! 🍾
