### ISSUE TITLE
Autocomplete Emoji Alternative Names

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/Freetime#181]
Always a minor annoyance of mine when I can't remember the exact name for an emoji (so autocomplete won't pick it up!)

Who knew 🎉  was `tada` 🤔 

Maybe revise to use something like this JSON file: https://github.com/github/gemoji/blob/master/db/emoji.json (from GitHub, so most likely to be up-to-date) and autocomplete on aliases and tags?

**Comment by rnystrom** [comment]
Omg, would have loved to find this stupid json file instead of formatting/cleaning the one I did by hand.........

I'm actually down to do this now. I also messed up with `:thinking:` not working.

We could actually update `GithubEmoji.swift` to use actual parsed objects from that file, then we could search the alias _and_ the name.

**Comment by Sherlouk** [comment]
> formatting/cleaning the one I did by hand.........

eek.. Sorry you had to do that 😅 

Some cool repos in here: https://github.com/showcases/emoji
May help 😄 

If no one else picks it up, I'll look into this tonight!
