### ISSUE TITLE
Event icon color 

### ISSUE THREAD

**Issue by dkhamsing** [rnystrom/Freetime#223]
Is there a way to get the event icon color?

See attached

![screen shot 2017-08-01 at 9 48 49 am](https://user-images.githubusercontent.com/4723115/28836664-ba6c6d4a-769e-11e7-9df6-0461abb31d02.png)

Here the pull request icon should be purple

**Comment by Sherlouk** [comment]
![image](https://user-images.githubusercontent.com/15193942/28837113-840a6e56-76e3-11e7-8b67-7efc56c442c6.png)

I've managed to get it working as part of the work in #200; the issue is the way the notifications are loaded has a very fixed payload which the last time I checked doesn't actually return the state.

**Comment by rnystrom** [comment]
Yup, not possible w/ the current [Notifications v3 API](https://developer.github.com/v3/activity/notifications/#list-your-notifications), and GraphQL does not support notifications. Would have to create a notifications middleware (server) for this that polls the v3 notifications for each user, then fetches the status of each issue/PR/commit. Lot of work that I don't really want to do, ha!

It'd be nice, but I've gotten used to it.
